In [1]:
import numpy as np


In [2]:
"This is a code"

'This is a code'

In [3]:
print(np.__version__)

1.22.1


In [4]:
a = np.array([[1,2,3],
              [67,89,34]])
b = np.array([[34,34,54],
              [74,89,53]])
c = a + b

In [5]:
print(c)

[[ 35  36  57]
 [141 178  87]]


In [6]:
d = a*b
print(d)

[[  34   68  162]
 [4958 7921 1802]]


In [7]:
i = np.eye(7)
print(i)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [8]:
a = np.array([x for x in range(27)])

o = a.reshape((3,3,3))

print(o)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [9]:
a = np.array([2,5,7,4,3])

o = a.astype('float')

print(o)

[2. 5. 7. 4. 3.]


In [10]:
a.dtype

dtype('int32')

In [11]:
a.shape

(5,)

In [12]:
zeros1 = np.zeros((2,5))
print(zeros1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
zeros1.reshape((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
a1 = np.array([[1,2],
               [3,4],
               [5,6]])

a2 = np.array([[7,8],
               [9,10],
               [10,11]])

o = np.vstack((a1, a2))

print(o)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [10 11]]


In [15]:
o = np.arange(0, 101, 2)

print(o)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [16]:
a = np.array([1,2,3,4,5])

b = np.array([1,3,2,4,5])

print(np.where(a == b))

(array([0, 3, 4], dtype=int64),)


In [17]:
ones1 = np.ones((15,3))
ones1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
x = np.sin(46)
x

0.9017883476488092

In [19]:
y = ones1.sum(axis=1)
y

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [20]:
print(ones1.T)
print(ones1.flat)
print(ones1.nbytes)
print(ones1.ndim)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
360
2


In [21]:
print(ones1.size)


45


In [22]:
f = 999
np.cbrt(f)

9.99666555493786

In [23]:
o = np.linspace(0, 1000, 75)

print(o)

[   0.           13.51351351   27.02702703   40.54054054   54.05405405
   67.56756757   81.08108108   94.59459459  108.10810811  121.62162162
  135.13513514  148.64864865  162.16216216  175.67567568  189.18918919
  202.7027027   216.21621622  229.72972973  243.24324324  256.75675676
  270.27027027  283.78378378  297.2972973   310.81081081  324.32432432
  337.83783784  351.35135135  364.86486486  378.37837838  391.89189189
  405.40540541  418.91891892  432.43243243  445.94594595  459.45945946
  472.97297297  486.48648649  500.          513.51351351  527.02702703
  540.54054054  554.05405405  567.56756757  581.08108108  594.59459459
  608.10810811  621.62162162  635.13513514  648.64864865  662.16216216
  675.67567568  689.18918919  702.7027027   716.21621622  729.72972973
  743.24324324  756.75675676  770.27027027  783.78378378  797.2972973
  810.81081081  824.32432432  837.83783784  851.35135135  864.86486486
  878.37837838  891.89189189  905.40540541  918.91891892  932.43243243
  945.9

In [24]:
print(np.tile(a1,9))

[[1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]
 [5 6 5 6 5 6 5 6 5 6 5 6 5 6 5 6 5 6]]


In [25]:
np.random.seed(123) 

o = np.random.randint(0, 10, size = (5,5))

print(o)

[[2 2 6 1 3]
 [9 6 1 0 1]
 [9 0 0 9 3]
 [4 0 0 4 1]
 [7 3 2 4 7]]


In [26]:
np.random.seed(123)

o = np.random.normal(size = (3,3))

print(o)

[[-1.0856306   0.99734545  0.2829785 ]
 [-1.50629471 -0.57860025  1.65143654]
 [-2.42667924 -0.42891263  1.26593626]]


In [27]:
rng1 = np.arange(45)
rng1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [28]:
rng1.reshape(5,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44]])

# THIS IS A HEADING

THIS IS A MARKDOWN